# Generated by Django 3.0.4 on 2020-04-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20200418_0145'),
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ManyToManyField(related_name='user_likes', to='Accounts.UserInfo')),
                ('post', models.ManyToManyField(related_name='post_likes', to='Posts.Post')),
            ],
        ),
    ]
